 typography: {
    fontFamily: '"Figtree", "Roboto", sans-serif',
    display1: {
      fontSize: '3rem',
      fontWeight: 600,
      lineHeight: '3.25rem',
      letterSpacing: '-0.02rem',
      fontFamily: 'quincy-cf, serif',
    },
    display2: {
      fontSize: '2.5rem',
      fontWeight: 600,
      lineHeight: '2.75rem',
      letterSpacing: '-0.05rem',
      fontFamily: 'quincy-cf, serif',
    },
    display3: {
      fontSize: '2.25rem',
      fontWeight: 600,
      lineHeight: '2.5rem',
      letterSpacing: '-0.03125rem',
      fontFamily: 'quincy-cf, serif',
    },
    display4: {
      fontSize: '1.75rem',
      fontWeight: 600,
      lineHeight: '2rem',
      letterSpacing: '-0.03125rem',
      fontFamily: 'quincy-cf, serif',
    },
    h1: {
      fontSize: '2.75rem',
      fontWeight: 600,
      lineHeight: '3rem',
      letterSpacing: '-0.0275rem',
    },
    h2: {
      fontSize: '2.25rem',
      fontWeight: 600,
      lineHeight: '2.75rem',
      letterSpacing: '-0.011875rem',
    },
    h3: {
      fontSize: '2rem',
      fontWeight: 600,
      lineHeight: '2.5rem',
      letterSpacing: '-0.01rem',
    },
    h4: {
      fontSize: '1.75rem',
      fontWeight: 600,
      letterSpacing: '-0.00875rem',
      lineHeight: '2.25rem',
    },
    h5: {
      fontSize: '1.5rem',
      fontWeight: 600,
      lineHeight: '2rem',
      letterSpacing: '-0.00625rem',
    },
    h6: {
      fontSize: '1.125rem',
      fontWeight: 600,
      lineHeight: '1.5rem',
      letterSpacing: '-0.00375rem',
    },
    subtitle1: {
      fontSize: '1rem',
      fontWeight: 600,
      lineHeight: '1.5rem',
      letterSpacing: '0rem',
    },
    subtitle2: {
      fontSize: '0.875rem',
      fontWeight: 600,
      lineHeight: '1.25rem',
      letterSpacing: '0rem',
    },
    overline: {
      fontSize: '0.875rem',
      fontWeight: 600,
      lineHeight: '1rem',
      letterSpacing: '0.075rem',
      textTransform: 'uppercase',
    },
    body1: {
      fontSize: '1rem',
      fontWeight: 400,
      lineHeight: '1.5rem',
      letterSpacing: '0rem',
    },
    body2: {
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: '1.25rem',
      letterSpacing: '0rem',
    },
    caption: {
      fontSize: '0.75rem',
      fontWeight: 400,
      lineHeight: '0.875rem',
      letterSpacing: '0rem',
    },
    button: {
      fontSize: '0.875rem',
      fontWeight: 600,
      lineHeight: '1.25rem',
      letterSpacing: '0.00938rem',
      textTransform: 'none',
    },